version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    executor:
      name: node/default
    resource_class: medium
    steps:
      - checkout
      - run: npm install
      - run: mkdir junit
      - run:
          command: npm run test
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit
